(define (problem taquin_problem)
(:domain TAQUIN)
(:objects A B C D E F G H I - position
          one two three four five six seven eight free - tile)
(:init (on A one)
(on B two)
(on C six)
(on D seven)
(on E three)
(on F four)
(on G free)
(on H five)
(on I eight)
(permutable A D)
(permutable A B)
(permutable B C)
(permutable B E)
(permutable B C)
(permutable C F)
(permutable D E)
(permutable E F)
(permutable D G)
(permutable G H)
(permutable E H)
(permutable H I)
(permutable F I))

(:goal (and (on A one)
(on B two)
(on C three)
(on D four)
(on E five)
(on F six)
(on G seven)
(on H eight)
(on I free)))
)
